import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import QRCode from "qrcode";
import imageBase64 from "@/images/logo-bg.png";

export const handleCustomerWisePDF = async (
  columns,
  data,
  title,
  customer,
  totals = null
) => {
  if (!data || data.length === 0) return;

  const user = JSON.parse(localStorage.getItem("user"));
  const doc = new jsPDF("p", "mm", "a4");
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const currentDate = new Date();
  const formattedDate = currentDate.toLocaleString("en-IN", {
    timeZone: "Asia/Kolkata",
    hour12: true,
  });

  // QR Code
  const qrText = `Generated by : ${user?.name}\nEmployee Id : ${user?.employeeId}\nGenerated at: ${formattedDate}`;
  const qrBase64 = await QRCode.toDataURL(qrText);

  // Convert Data
  const modifiedData = data.map((row) => columns.map((col) => row[col] ?? ""));

  if (totals) {
    const emptyCells = Array(columns.length - 3).fill("");
    modifiedData.push([...emptyCells, "Totals", totals.bags, totals.tonnes]);
  }

  // Header + Footer
  const drawFooterAndHeader = () => {
    const pageNumber = doc.internal.getCurrentPageInfo().pageNumber;
    const pageCount = doc.internal.getNumberOfPages();

    // Logo
    if (imageBase64) {
      doc.addImage(imageBase64, "PNG", 10, 10, 40, 20);
    }

    // QR
    if (qrBase64) {
      doc.addImage(qrBase64, "PNG", pageWidth - 45, 10, 30, 30);
    }

    // Title
    doc.setFontSize(14);
    doc.text(title, pageWidth / 2, 20, { align: "center" });

    doc.setFontSize(9);
    doc.setTextColor(80);
    doc.text(`Generated on: ${formattedDate}`, pageWidth / 2, 28, {
      align: "center",
    });

    // Divider
    doc.setDrawColor(0);
    doc.line(10, 38, pageWidth - 10, 38);

    // Footer
    doc.setDrawColor(0);
    doc.setLineWidth(0.1);
    doc.line(10, pageHeight - 30, pageWidth - 10, pageHeight - 30);

    const footerLines = [
      "Registered Address : Flat No. 203, Mar Homes, Annojiguda, Pocharam, Korremal, Hyderabad, Telangana, India - 500088.",
      "This is an electronically generated document, no signature is required.",
    ];
    doc.setFontSize(8);
    footerLines.forEach((line, i) => {
      doc.setTextColor(150);
      doc.text(line, pageWidth / 2, pageHeight - 22 + i * 4, {
        align: "center",
      });
    });

    doc.setTextColor("#a92427");
    doc.text(
      "© Kernn Automations Private Limited",
      pageWidth / 2,
      pageHeight - 22 + footerLines.length * 4,
      { align: "center" }
    );

    doc.setTextColor(0);
    doc.text(
      `Page ${pageNumber} of ${pageCount}`,
      pageWidth - 40,
      pageHeight - 10
    );
  };

  // Add Customer Details Block
  let customerDetailsY = 45;
  doc.setFontSize(11);
  doc.setTextColor(0);
  doc.text(`Customer Name : ${customer?.name || "-"}`, 14, customerDetailsY);
  doc.text(
    `Customer ID   : ${customer?.customer_id || "-"}`,
    14,
    customerDetailsY + 6
  );
  doc.text(
    `Mobile        : ${customer?.mobile || "-"}`,
    14,
    customerDetailsY + 12
  );

  let address = [
    customer?.firmname,
    customer?.city,
    customer?.district,
    customer?.state,
    customer?.pincode,
  ]
    .filter(Boolean)
    .join(", ");

  doc.text(`Address       : ${address || "-"}`, 14, customerDetailsY + 18);

  // Table
  autoTable(doc, {
    head: [columns],
    body: modifiedData,
    headStyles: { fillColor: [0, 49, 118], textColor: [255, 255, 255] },
    bodyStyles: { textColor: [0, 0, 0], fontSize: 9 },
    margin: { top: 75, bottom: 40 },
    startY: 75,
    didDrawPage: drawFooterAndHeader,
  });

  doc.save(`${title}.pdf`);
};
